CREATE TABLE `WHV_USER` (
  `USER_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `STATUS` varchar(10) NOT NULL COMMENT '状态',
  `PASSPORT_NUM` varchar(20) NOT NULL COMMENT '护照号',
  `FIRST_NAME` varchar(20) NOT NULL COMMENT '名字',
  `LAST_NAME` varchar(20) NOT NULL COMMENT '姓氏',
  `EMAIL` varchar(20) NOT NULL COMMENT '邮箱',
  `PASSWORD` varchar(20) NOT NULL COMMENT '密码',
  `SEX` int(11) DEFAULT NULL COMMENT '性别',
  `PHONE_NO` varchar(20) DEFAULT NULL COMMENT '手机号',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME` datetime DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_PASSPORT_NUM` (`PASSPORT_NUM`))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';
